version: '3.8'

services:
  db:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DBNAME}
    ports:
      - "5432:5432"
    volumes:
      - ./1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./2-data.sql:/docker-entrypoint-initdb.d/2-data.sql
